import type { LobbyScenario } from './lobbyScenarios'

export const nachtScenarios: LobbyScenario[] = [
  {
    id: 'nacht-verpaetete-ankunft',
    category: 'checkin',
    pressure: 'medium',
    guestLineDe: '„Guten Abend, ich bin später als geplant angekommen. Die Reservierung läuft auf den Namen Neumann – können Sie kurz nachsehen?“',
    situationEn: 'A fictional late arrival needs a calm check before the quiet night gets any busier.',
    situationId: 'Tamu fiktif datang terlambat dan butuh pemeriksaan yang tenang sebelum malam menjadi lebih sibuk.',
    options: [
      {
        id: 'a',
        textDe: '„Guten Abend und willkommen. Ich schaue kurz nach Ihrer Reservierung und sage Ihnen gleich, wie es weitergeht.“',
        effects: { satisfaction: 1, composure: 1, timeCostSec: 20 },
        tags: ['welcome', 'verify'],
      },
      {
        id: 'b',
        textDe: '„Wenn Sie den Namen schon genannt haben, wird das schon passen. Warten Sie bitte dort.“',
        effects: { satisfaction: -1, composure: 0, timeCostSec: 5 },
        tags: ['dismissive'],
      },
      {
        id: 'c',
        textDe: '„Sagen Sie mir nur schnell eine Zimmernummer, dann überspringen wir die Prüfung.“',
        effects: { satisfaction: 0, composure: -2, timeCostSec: 10 },
        tags: ['shortcut', 'risky'],
      },
    ],
    bestOptionId: 'a',
    rationaleId: 'Opsi a paling aman karena menyambut tamu, memeriksa informasi yang ada, dan memberi langkah berikutnya tanpa membuat janji berlebihan. Opsi b terdengar dingin, sedangkan opsi c melewati pemeriksaan yang penting.',
    shiftReportLine: 'Späte Ankunft: ruhig geprüft, freundlich gelandet.',
    tags: ['arrival', 'night'],
  },
  {
    id: 'nacht-flur-geraeusch',
    category: 'complaint',
    pressure: 'high',
    guestLineDe: '„Entschuldigung, auf dem Flur ist seit zehn Minuten so ein Lärm. Ich möchte wirklich schlafen.“',
    situationEn: 'A fictional guest reports corridor noise during the quietest part of the night.',
    situationId: 'Tamu fiktif melaporkan suara berisik di koridor saat malam paling sunyi.',
    options: [
      {
        id: 'a',
        textDe: '„Das klingt wirklich störend. Ich kümmere mich darum und komme gleich mit einem ruhigen nächsten Schritt zurück.“',
        effects: { satisfaction: 2, composure: 0, timeCostSec: 25 },
        tags: ['validate', 'deescalate'],
      },
      {
        id: 'b',
        textDe: '„Nachts ist es eben nie ganz leise. Versuchen Sie einfach, darüber hinwegzuhören.“',
        effects: { satisfaction: -2, composure: 0, timeCostSec: 5 },
        tags: ['dismissive'],
      },
      {
        id: 'c',
        textDe: '„Gehen Sie doch selbst auf den Flur und sagen Sie den Leuten Bescheid.“',
        effects: { satisfaction: -1, composure: -1, timeCostSec: 10 },
        tags: ['deflect'],
      },
    ],
    bestOptionId: 'a',
    rationaleId: 'Opsi a memvalidasi keluhan dan menurunkan tensi karena tamu merasa didengar. Opsi b mengecilkan masalah, sementara opsi c melempar konflik kembali ke tamu. Malam tetap tenang tanpa drama tambahan.',
    shiftReportLine: 'Flurgeräusch: deeskaliert, Nachtruhe wieder im grünen Bereich.',
    tags: ['noise', 'night'],
  },
  {
    id: 'nacht-fruehes-taxi',
    category: 'checkout',
    pressure: 'medium',
    guestLineDe: '„Mein Taxi soll um 04:15 Uhr kommen. Können Sie bitte kurz bestätigen, dass die Anfrage angekommen ist?“',
    situationEn: 'A fictional early departure needs a clear taxi confirmation before the guest tries to sleep again.',
    situationId: 'Tamu fiktif akan berangkat sangat pagi dan ingin konfirmasi taksi yang jelas sebelum tidur lagi.',
    options: [
      {
        id: 'a',
        textDe: '„Gern, ich schaue kurz nach dem Eintrag und bestätige Ihnen dann, was dort steht.“',
        effects: { satisfaction: 2, composure: 1, timeCostSec: 20 },
        tags: ['confirm', 'clear'],
      },
      {
        id: 'b',
        textDe: '„Das Taxi kommt bestimmt. Ich verspreche es Ihnen einfach.“',
        effects: { satisfaction: 1, composure: -1, timeCostSec: 5 },
        tags: ['overpromise'],
      },
      {
        id: 'c',
        textDe: '„Keine Ahnung, ich bin erst seit fünf Minuten hier.“',
        effects: { satisfaction: -1, composure: 0, timeCostSec: 5 },
        tags: ['brush-off'],
      },
    ],
    bestOptionId: 'a',
    rationaleId: 'Opsi a memberi kepastian yang jujur karena yang dikonfirmasi adalah informasi yang benar-benar tersedia. Opsi b menenangkan sesaat tetapi membuat janji yang belum tentu benar. Opsi c jujur, namun tidak membantu tamu.',
    shiftReportLine: 'Frühtaxi: Eintrag bestätigt, Wecker kann klingeln.',
    tags: ['taxi', 'early-departure'],
  },
  {
    id: 'nacht-kaffeemaschine-0300',
    category: 'system',
    pressure: 'system',
    guestLineDe: '„Es ist drei Uhr und die Kaffeemaschine macht nur noch ein Geräusch. Haben Sie vielleicht einen Tipp?“',
    situationEn: 'At 03:00, a fictional coffee-machine failure becomes the most important incident in the building.',
    situationId: 'Jam 03:00, mesin kopi fiktif rusak dan mendadak menjadi insiden paling penting di gedung.',
    options: [
      {
        id: 'a',
        textDe: '„Oh nein. Ich schaue kurz, ob noch eine einfache Alternative bereitsteht, und bleibe bei Ihnen, bis wir eine haben.“',
        effects: { satisfaction: 2, composure: 1, timeCostSec: 30 },
        tags: ['care', 'fallback'],
      },
      {
        id: 'b',
        textDe: '„Drücken Sie einfach noch ein paar Mal auf den Knopf. Vielleicht merkt sie es dann.“',
        effects: { satisfaction: 0, composure: -1, timeCostSec: 15 },
        tags: ['guess'],
      },
      {
        id: 'c',
        textDe: '„Um drei Uhr gibt es keinen Kaffee mehr. Gute Nacht.“',
        effects: { satisfaction: -2, composure: 0, timeCostSec: 5 },
        tags: ['curt'],
      },
    ],
    bestOptionId: 'a',
    rationaleId: 'Opsi a mengakui masalah dan mencari alternatif sederhana karena kebutuhan tamu tetap nyata walaupun mesinnya gagal. Opsi b hanya menebak-nebak, sedangkan opsi c benar-benar menutup percakapan tanpa solusi.',
    shiftReportLine: '03:00-Kaffee: Maschine müde, Alternative gefunden.',
    tags: ['coffee', 'system', '03:00'],
  },
]
